import type { NextPage } from "next";
import Head from "next/head";
import { Box, Button, Heading, useDisclosure } from "@chakra-ui/react";
import { CryptoConverterForm } from "components/CryptoConverterForm";
import { WalletDetailsModal } from "components/WalletDetailsModal";
import { useEffect } from "react";
import { metaMask } from "connectors/metamask";

const Home: NextPage = () => {
  const { isOpen, onClose, onOpen } = useDisclosure();

  useEffect(() => {
    void metaMask.connectEagerly();
  }, []);

  return (
    <>
      <Head>
        <title>Neptune Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        bgColor="gray.700"
        d="flex"
        flexDir="column"
        minH="100vh"
        minW="100vw"
        alignItems="center"
        justifyContent="center"
      >
        <Box
          p="30px"
          borderWidth="1px"
          mb="30px"
          rounded="md"
          bgColor="gray.50"
        >
          <Heading mb="30px" size="lg">
            Crypto Converter
          </Heading>
          <CryptoConverterForm
            fromCurrency="NEP"
            toCurrency="BUSD"
            exchangeRate={3}
          />
        </Box>
        <Button variant="link" colorScheme="blue" onClick={onOpen}>
          Check Wallet Details
        </Button>
        <WalletDetailsModal isOpen={isOpen} onClose={onClose} isCentered />
      </Box>
    </>
  );
};

export default Home;
